name: dream_journal
description: A Flutter dream journal application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  table_calendar: ^3.0.9
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  path_provider: ^2.0.11
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.1.0
  dynamic_color: ^1.6.6
  pdf: ^3.10.8
  printing: ^5.11.0
  audioplayers: ^5.2.1
  record: ^6.0.0
  waveform_flutter: 1.2.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
